04-11 22:39:54 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER_SESSION" が見つかりません
Table "USER_SESSION" not found; SQL statement:
UPDATE USER_SESSION SET SESSION_OBJECT=?,EXPIRATION_DATETIME=? WHERE SESSION_ID = ? [42102-176]
04-11 22:40:12 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER_SESSION" が見つかりません
Table "USER_SESSION" not found; SQL statement:
UPDATE USER_SESSION SET SESSION_OBJECT=?,EXPIRATION_DATETIME=? WHERE SESSION_ID = ? [42102-176]
04-11 22:41:05 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER_SESSION" が見つかりません
Table "USER_SESSION" not found; SQL statement:
UPDATE USER_SESSION SET SESSION_OBJECT=?,EXPIRATION_DATETIME=? WHERE SESSION_ID = ? [42102-176]
04-11 22:44:30 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "USER_SESSION" が見つかりません
Table "USER_SESSION" not found; SQL statement:
UPDATE USER_SESSION SET SESSION_OBJECT=?,EXPIRATION_DATETIME=? WHERE SESSION_ID = ? [42102-176]
04-18 22:54:55 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "DOG_DTO" が見つかりません
Table "DOG_DTO" not found; SQL statement:
SELECT COLOR,ID,NAME FROM DOG_DTO [42102-176]
05-28 20:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
create table permission(
  permission_id(10),
  PRIMARY KEY (permission_id)
) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
create table permission_request(
  permission_id(10),
  request_id varchar(10),
  PRIMARY KEY (permission_id, request_id)
) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
create table group_permission(
  group_id varchar(10),
  permission_id(10),
  PRIMARY KEY (group_id, check_id)
) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:53:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 不明なデータ型: "("
Unknown data type: "("; SQL statement:
create table system_account_permission(
  user_id varchar(10),
  permission_id(10),
  PRIMARY KEY (group_id, permission_id)
) [50004-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3963)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3826)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5723)
	at org.h2.command.Parser.parseCreate(Parser.java:4122)
	at org.h2.command.Parser.parsePrepared(Parser.java:351)
	at org.h2.command.Parser.parse(Parser.java:306)
	at org.h2.command.Parser.parse(Parser.java:278)
	at org.h2.command.Parser.prepareCommand(Parser.java:243)
	at org.h2.engine.Session.prepareLocal(Session.java:442)
	at org.h2.engine.Session.prepareCommand(Session.java:384)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:172)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:54:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "GROUP_ID" はすでに存在します
Table "GROUP_ID" already exists; SQL statement:
create table group_id(
  group_id varchar(10),
  primary key (group_id)
) [42101-176]
05-28 20:54:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "SYSTEM_ACCOUNT" はすでに存在します
Table "SYSTEM_ACCOUNT" already exists; SQL statement:
create table system_account(
  user_id varchar(10),
  user_lock char(1),
  from_date TIMESTAMP,
  to_date TIMESTAMP,
  user_name varchar(20),
  PRIMARY KEY (user_id)
) [42101-176]
05-28 20:54:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "GROUP_SYSTEM_ACCOUNT" はすでに存在します
Table "GROUP_SYSTEM_ACCOUNT" already exists; SQL statement:
create table group_system_account(
  group_id varchar(10),
  user_id varchar(10),
  from_date TIMESTAMP,
  to_date TIMESTAMP,
  PRIMARY KEY (group_id, user_id, from_date)
) [42101-176]
05-28 20:54:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "REQUEST" はすでに存在します
Table "REQUEST" already exists; SQL statement:
create table request(
  request_id varchar(10),
  PRIMARY KEY (request_id)
) [42101-176]
05-28 20:54:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 列 "CHECK_ID" が見つかりません
Column "CHECK_ID" not found; SQL statement:
create table group_permission(
  group_id varchar(10),
  permission_id varchar(10),
  PRIMARY KEY (group_id, check_id)
) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:108)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:54:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 列 "GROUP_ID" が見つかりません
Column "GROUP_ID" not found; SQL statement:
create table system_account_permission(
  user_id varchar(10),
  permission_id varchar(10),
  PRIMARY KEY (group_id, permission_id)
) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:108)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "GROUP_ID" はすでに存在します
Table "GROUP_ID" already exists; SQL statement:
create table group_id(
  group_id varchar(10),
  primary key (group_id)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "SYSTEM_ACCOUNT" はすでに存在します
Table "SYSTEM_ACCOUNT" already exists; SQL statement:
create table system_account(
  user_id varchar(10),
  user_lock char(1),
  from_date TIMESTAMP,
  to_date TIMESTAMP,
  user_name varchar(20),
  PRIMARY KEY (user_id)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "GROUP_SYSTEM_ACCOUNT" はすでに存在します
Table "GROUP_SYSTEM_ACCOUNT" already exists; SQL statement:
create table group_system_account(
  group_id varchar(10),
  user_id varchar(10),
  from_date TIMESTAMP,
  to_date TIMESTAMP,
  PRIMARY KEY (group_id, user_id, from_date)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "PERMISSION" はすでに存在します
Table "PERMISSION" already exists; SQL statement:
create table permission(
  permission_id varchar(10),
  PRIMARY KEY (permission_id)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "PERMISSION_REQUEST" はすでに存在します
Table "PERMISSION_REQUEST" already exists; SQL statement:
create table permission_request(
  permission_id varchar(10),
  request_id varchar(10),
  PRIMARY KEY (permission_id, request_id)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "REQUEST" はすでに存在します
Table "REQUEST" already exists; SQL statement:
create table request(
  request_id varchar(10),
  PRIMARY KEY (request_id)
) [42101-176]
05-28 20:54:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: 列 "GROUP_ID" が見つかりません
Column "GROUP_ID" not found; SQL statement:
create table system_account_permission(
  user_id varchar(10),
  permission_id varchar(10),
  PRIMARY KEY (group_id, permission_id)
) [42122-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.table.Table.getColumn(Table.java:637)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:108)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:73)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:170)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
05-28 21:33:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: "TIMESTAMP" 定数 "2019/05/25 00:00:00" を解析できません
Cannot parse "TIMESTAMP" constant "2019/05/25 00:00:00"; SQL statement:
insert into system_account values('1', '0', '2019/05/25 00:00:00', '2019/05/25 00:00:00', 'なぶ　太郎') -- ('1', '0', '2019/05/25 00:00:00', '2019/05/25 00:00:00', STRINGDECODE('\u306a\u3076\u3000\u592a\u90ce')) [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:88)
	at org.h2.value.Value.convertTo(Value.java:862)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 2019/05/25 00:00:00
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:106)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:86)
	... 15 more
05-28 21:34:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: "TIMESTAMP" 定数 "2019/05/25 00:00:00.000" を解析できません
Cannot parse "TIMESTAMP" constant "2019/05/25 00:00:00.000"; SQL statement:
insert into system_account values('1', '0', '2019/05/25 00:00:00.000', '2019/05/25 00:00:00.000', 'なぶ　太郎') -- ('1', '0', '2019/05/25 00:00:00.000', '2019/05/25 00:00:00.000', STRINGDECODE('\u306a\u3076\u3000\u592a\u90ce')) [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:88)
	at org.h2.value.Value.convertTo(Value.java:862)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 2019/05/25 00:00:00.000
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:106)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:86)
	... 15 more
05-28 21:34:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: "TIMESTAMP" 定数 "2019/05/25" を解析できません
Cannot parse "TIMESTAMP" constant "2019/05/25"; SQL statement:
insert into system_account values('1', '0', '2019/05/25', '2019/05/25', 'なぶ　太郎') -- ('1', '0', '2019/05/25', '2019/05/25', STRINGDECODE('\u306a\u3076\u3000\u592a\u90ce')) [22007-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:88)
	at org.h2.value.Value.convertTo(Value.java:862)
	at org.h2.table.Column.convert(Column.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:144)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:160)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1391)
	at org.h2.server.web.WebApp.query(WebApp.java:1064)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1026)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1013)
	at org.h2.server.web.WebThread.process(WebThread.java:168)
	at org.h2.server.web.WebThread.run(WebThread.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 2019/05/25
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:273)
	at org.h2.value.ValueTimestamp.parseTry(ValueTimestamp.java:106)
	at org.h2.value.ValueTimestamp.parse(ValueTimestamp.java:86)
	... 15 more
06-04 23:06:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: テーブル "FORM" が見つかりません
Table "FORM" not found; SQL statement:
delete form system_account [42102-176]
06-07 01:02:57 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: パラメータ "SQL" に対する値 "null" が不正です
Invalid value "null" for parameter "SQL" [90008-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:227)
	at org.h2.jdbc.JdbcConnection.translateSQL(JdbcConnection.java:1278)
	at org.h2.jdbc.JdbcConnection.translateSQL(JdbcConnection.java:1265)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:275)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at nablarch.core.db.statement.BasicStatementFactory.getSqlPStatement(BasicStatementFactory.java:56)
	at nablarch.core.db.connection.BasicDbConnection$1.createSqlStatement(BasicDbConnection.java:193)
	at nablarch.core.db.connection.BasicDbConnection$StatementCreator.create(BasicDbConnection.java:637)
	at nablarch.core.db.connection.BasicDbConnection.prepareStatement(BasicDbConnection.java:201)
	at nablarch.core.date.BasicBusinessDateProvider.getDateByUnCondition(BasicBusinessDateProvider.java:335)
	at nablarch.core.date.BasicBusinessDateProvider.access$100(BasicBusinessDateProvider.java:87)
	at nablarch.core.date.BasicBusinessDateProvider$2.execute(BasicBusinessDateProvider.java:303)
	at nablarch.core.date.BasicBusinessDateProvider$2.execute(BasicBusinessDateProvider.java:300)
	at nablarch.core.db.transaction.SimpleDbTransactionExecutor.doTransaction(SimpleDbTransactionExecutor.java:52)
	at nablarch.core.date.BasicBusinessDateProvider.getAllBusinessDate(BasicBusinessDateProvider.java:299)
	at nablarch.core.date.BasicBusinessDateProvider.getCacheData(BasicBusinessDateProvider.java:510)
	at nablarch.core.date.BasicBusinessDateProvider.getDate(BasicBusinessDateProvider.java:227)
	at nablarch.core.date.BasicBusinessDateProvider.getDate(BasicBusinessDateProvider.java:210)
	at nablarch.common.permission.BasicPermissionFactory.getPermission(BasicPermissionFactory.java:149)
	at nablarch.common.permission.PermissionCheckHandler.handle(PermissionCheckHandler.java:76)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at jp.co.handler.LoginCheckHandler.handle(LoginCheckHandler.java:40)
	at jp.co.handler.LoginCheckHandler.handle(LoginCheckHandler.java:15)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.common.web.session.SessionStoreHandler.handle(SessionStoreHandler.java:108)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.upload.MultipartHandler.handle(MultipartHandler.java:80)
	at nablarch.fw.web.upload.MultipartHandler.handle(MultipartHandler.java:48)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:36)
	at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:25)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:139)
	at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:42)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:42)
	at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:32)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.HttpCharacterEncodingHandler.handle(HttpCharacterEncodingHandler.java:103)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.servlet.WebFrontController.doFilter(WebFrontController.java:101)
	at nablarch.fw.web.servlet.RepositoryBasedWebFrontController.doFilter(RepositoryBasedWebFrontController.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
06-07 01:08:33 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: パラメータ "SQL" に対する値 "null" が不正です
Invalid value "null" for parameter "SQL" [90008-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.getInvalidValueException(DbException.java:227)
	at org.h2.jdbc.JdbcConnection.translateSQL(JdbcConnection.java:1278)
	at org.h2.jdbc.JdbcConnection.translateSQL(JdbcConnection.java:1265)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:275)
	at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
	at nablarch.core.db.statement.BasicStatementFactory.getSqlPStatement(BasicStatementFactory.java:56)
	at nablarch.core.db.connection.BasicDbConnection$1.createSqlStatement(BasicDbConnection.java:193)
	at nablarch.core.db.connection.BasicDbConnection$StatementCreator.create(BasicDbConnection.java:637)
	at nablarch.core.db.connection.BasicDbConnection.prepareStatement(BasicDbConnection.java:201)
	at nablarch.core.date.BasicBusinessDateProvider.getDateByUnCondition(BasicBusinessDateProvider.java:335)
	at nablarch.core.date.BasicBusinessDateProvider.access$100(BasicBusinessDateProvider.java:87)
	at nablarch.core.date.BasicBusinessDateProvider$2.execute(BasicBusinessDateProvider.java:303)
	at nablarch.core.date.BasicBusinessDateProvider$2.execute(BasicBusinessDateProvider.java:300)
	at nablarch.core.db.transaction.SimpleDbTransactionExecutor.doTransaction(SimpleDbTransactionExecutor.java:52)
	at nablarch.core.date.BasicBusinessDateProvider.getAllBusinessDate(BasicBusinessDateProvider.java:299)
	at nablarch.core.date.BasicBusinessDateProvider.getCacheData(BasicBusinessDateProvider.java:510)
	at nablarch.core.date.BasicBusinessDateProvider.getDate(BasicBusinessDateProvider.java:227)
	at nablarch.core.date.BasicBusinessDateProvider.getDate(BasicBusinessDateProvider.java:210)
	at nablarch.common.permission.BasicPermissionFactory.getPermission(BasicPermissionFactory.java:149)
	at nablarch.common.permission.PermissionCheckHandler.handle(PermissionCheckHandler.java:76)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at jp.co.handler.LoginCheckHandler.handle(LoginCheckHandler.java:40)
	at jp.co.handler.LoginCheckHandler.handle(LoginCheckHandler.java:15)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.common.web.session.SessionStoreHandler.handle(SessionStoreHandler.java:108)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.upload.MultipartHandler.handle(MultipartHandler.java:80)
	at nablarch.fw.web.upload.MultipartHandler.handle(MultipartHandler.java:48)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:36)
	at nablarch.fw.web.handler.SecureHandler.handle(SecureHandler.java:25)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:139)
	at nablarch.fw.web.handler.HttpResponseHandler.handle(HttpResponseHandler.java:42)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:42)
	at nablarch.fw.handler.GlobalErrorHandler.handle(GlobalErrorHandler.java:32)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.handler.HttpCharacterEncodingHandler.handle(HttpCharacterEncodingHandler.java:103)
	at nablarch.fw.ExecutionContext.handleNext(ExecutionContext.java:95)
	at nablarch.fw.web.servlet.WebFrontController.doFilter(WebFrontController.java:101)
	at nablarch.fw.web.servlet.RepositoryBasedWebFrontController.doFilter(RepositoryBasedWebFrontController.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
06-07 01:14:06 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: テーブル "BUSINESS_DATE" が見つかりません
Table "BUSINESS_DATE" not found; SQL statement:
SELECT SEGMENT_ID, BIZ_DATE FROM BUSINESS_DATE  [42102-176]
